### ISSUE TITLE
Fix {FileCDN}/getSignedUrl endpoints to accept fileName

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/inbound#51]
Currently, all these endpoints fetch static responses from the FileCDNs. We need to fix them and accept fileName from the request body.

These are the endpoints:

`/minio/getSignedUrl`
`/azure/getSignedUrl`
`/sunbird/getSignedUrl`

**Comment by susheelvar** [comment]
@chinmoy12c closed development. Unit tests completed, working fine.
