### ISSUE TITLE
Remove old implementation of getLatestXMessage

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/inbound#74]
The [processBotMessage](https://github.com/samagra-comms/inbound/blob/a6ead7c809dfeb3d44e79e05d7177031a0358f3a/src/main/java/com/uci/inbound/utils/XMsgProcessingUtil.java#L210) method uses the old and slow implementation of [getLatestXMessage](https://github.com/samagra-comms/inbound/blob/a6ead7c809dfeb3d44e79e05d7177031a0358f3a/src/main/java/com/uci/inbound/utils/XMsgProcessingUtil.java#L353C3-L353C3). We need to remove this implementation and use only this one [here](https://github.com/samagra-comms/inbound/blob/a6ead7c809dfeb3d44e79e05d7177031a0358f3a/src/main/java/com/uci/inbound/utils/XMsgProcessingUtil.java#L508C1-L508C1).

**Comment by pankajjangid05** [comment]
Hey @chinmoy12c 

Please review this PR and approve it [link](https://github.com/samagra-comms/inbound/pull/76)

**Comment by pankajjangid05** [comment]
Code is merge with master and deployed on prod

**Comment by pankajjangid05** [comment]
Code is working tested on prod and staging.
