### ISSUE TITLE
[Bug] - NL APP Notification Delivery Report API

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/inbound#81]
The problem is Unable to fetch data from Cassandra due to messageId being different.

**Comment by karntrehan** [comment]
Dev done. Testing locally.

**Comment by geeky-abhishek** [comment]
Testing is in progress

**Comment by pankajjangid05** [comment]
@chinmoy12c Please review this PR : https://github.com/samagra-comms/inbound/pull/83/commits/00f3feb2ff9993763c25de37bfc9541b4db68273

**Comment by pankajjangid05** [comment]
The code is deployed on staging.

**Comment by pankajjangid05** [comment]
Tested on staging. We also need to test on prod.

**Comment by geeky-abhishek** [comment]
To be closed after deployment on PROD
