### ISSUE TITLE
Increase Minio Signed URL Expiry Time for NL-APP

### ISSUE THREAD

**Issue by pankajjangid05** [samagra-comms/inbound#82]
We need to increase the minio signed url expiry time. Currently, the expiry time is 1 day.

**Comment by karntrehan** [comment]
Dev done. Testing locally.

**Comment by pankajjangid05** [comment]
@chinmoy12c Please review this PR https://github.com/samagra-comms/adapter/pull/52

**Comment by geeky-abhishek** [comment]
@chinmoy12c to review the PR.

**Comment by pankajjangid05** [comment]
The code is deployed on staging.

**Comment by chinmoy12c** [comment]
Currently, the token is expiring in 30-40 minutes as checked on Friday. Need to resolve this issue for Minio.

**Comment by geeky-abhishek** [comment]
@pankajjangid05 to connect with @ChakshuGautam

**Comment by pankajjangid05** [comment]
Resolved by @chinmoy12c.

**Comment by chinmoy12c** [comment]
Since the bucket was public, direct link access can be used instead of a signed url.

**Comment by karntrehan** [comment]
Tested on staging. To be deployed to prod.
