### ISSUE TITLE
Cassandra queries review

### ISSUE THREAD

**Issue by chinmoy12c** [samagra-comms/inbound#93]
Action Items:

- [x] Query based on timestamp only on the broadcast report and filter in code.
- [ ] Review and document the usage of other Cassandra queries and figure out if they can be cached or avoided.

**Comment by chinmoy12c** [comment]
Sheet to keep track of queries:
https://docs.google.com/spreadsheets/d/13f8TOblzObdmOPI41CJ6cuE_rNe07oXXc4hUKBz1vZ8/edit#gid=0

**Comment by karntrehan** [comment]
To pick changes mentioned here as a separate ticket.
